name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Sadece main branch'e push yapıldığında çalışır
  workflow_dispatch:  # Manuel olarak tetikleme imkanı verir

# GITHUB_TOKEN haklarını ayarlar
permissions:
  contents: read
  pages: write
  id-token: write

# Eşzamanlı deployment'ları engeller
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Tüm repo içeriğini yükler
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 